FROM alpine
RUN  mkdir -p /var/www/html/school-events-mobile/dist/
RUN  mkdir -p /var/www/html/share/
ADD ./dist/  /var/www/html/school-events-mobile/dist/
WORKDIR /var/www/html/school-events-mobile/dist/


