const detailConf = [
    {
        posterConfig: {
            pixelRatio: 3,
            width: 570,
            height: 826,
            debug: false,
            texts: [
                {
                    x: 60,
                    y: 590,
                    text: '',
                    fontSize: 30,
                    color: '#333',
                    opacity: 1,
                    marginRight: 10,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1210,
                    textOverflow: 'ellipsis',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/h5/aitiaozhan-poster.png',
                    width: 570,
                    height: 826,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 469,
                    height: 315,
                    y: 233,
                    x: 50,
                },
                {
                    url: '',
                    width: 142,
                    height: 142,
                    y: 666,
                    x: 380,
                    borderRadius: 140,
                },
            ],
        },
        titleList: [
            [
                '我的作品《',
                'resource_name',
                '》，【我正在参加青少年爱挑战活动】,快来给我点赞吧！',
            ],
        ],
    },
    {
        posterConfig: {},
        titleList: [
            [
                '我的作品《',
                'resource_name',
                '》，我正在参加才艺秀活动】,快来给我点赞吧！',
            ],
        ],
    },
    {
        posterConfig: {
            width: 520,
            height: 730,
            debug: false,
            texts: [
                {
                    x: 50,
                    y: 505,
                    text: '#唱歌#',
                    fontSize: 29,
                    color: '#FFE49C',
                    opacity: 1,
                    marginRight: 10,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1210,
                    textOverflow: 'ellipsis',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/share.png',
                    width: 520,
                    height: 730,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 420,
                    height: 282,
                    y: 185,
                    x: 50,
                },
                {
                    url: '',
                    width: 142,
                    height: 142,
                    y: 573,
                    x: 348,
                },
            ],
        },
        titleList: [
            ['我正在参加“才艺拜大年”有奖征集活动，快来帮我投票吧～'],
            ['才艺拜大年，好礼送不停，我需要你宝贵的一票！'],
        ],
    },
    {
        posterConfig: {
            width: 570,
            height: 820,
            debug: false,
            texts: [
                {
                    x: 60,
                    y: 583,
                    text: '',
                    fontSize: 29,
                    color: '#FF2E3F',
                    opacity: 1,
                    marginRight: 10,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1210,
                    textOverflow: 'ellipsis',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/poster01.png',
                    width: 570,
                    height: 820,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 469,
                    height: 315,
                    y: 233,
                    x: 50,
                },
                {
                    url: '',
                    width: 142,
                    height: 142,
                    y: 645,
                    x: 348,
                },
            ],
        },
        titleList: [
            [
                '一幅幅春节影像作品，是最想留下的幸福瞬间！我的春节作品，正在等你来投票哦！',
            ],
            ['记录新年，赢大奖！小伙伴们快来帮我投票吧～～'],
            ['快来看我记录的春节快乐瞬间！请为我投票，晒年味，赢好礼！'],
            ['快来看我家的新年有什么不一样！快来为我投票吧！晒年俗，赢大奖！'],
            ['家家“年味”各不同，快来围观我家的欢乐新年吧～别忘了投票哦！'],
            ['嗨～我在参加“记录新年赢大奖”活动，动动手指为我投票吧！'],
        ],
    },
    {
        posterConfig: {
            width: 570,
            height: 820,
            debug: false,
            texts: [
                {
                    x: 60,
                    y: 583,
                    text: '',
                    fontSize: 29,
                    color: '#fff',
                    opacity: 1,
                    marginRight: 10,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1210,
                    textOverflow: 'ellipsis',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'http://aitiaozhan.oss-cn-beijing.aliyuncs.com/chunjiehao/yiqing-poster.png',
                    width: 570,
                    height: 820,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 469,
                    height: 315,
                    y: 233,
                    x: 50,
                },
                {
                    url: '',
                    width: 142,
                    height: 142,
                    y: 645,
                    x: 348,
                },
            ],
        },
        titleList: [
            [
                '我的抗击疫情作品《',
                'resource_name',
                '》，为我点赞一起为武汉加油！',
            ],
            [
                '为爱出发，为武汉加油，我的作品《',
                'resource_name',
                '》向抗疫英雄致敬！',
            ],
            [
                '我的抗击疫情作品《',
                'resource_name',
                '》，大家“艺”起来，为武汉加油！',
            ],
        ],
    },
    {
        posterConfig: {
            width: 570,
            height: 820,
            debug: false,
            texts: [
                {
                    x: 60,
                    y: 583,
                    text: '',
                    fontSize: 29,
                    color: '#04A875',
                    opacity: 1,
                    marginRight: 10,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1210,
                    textOverflow: 'ellipsis',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/h5/read-poster.png',
                    width: 570,
                    height: 820,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 469,
                    height: 315,
                    y: 233,
                    x: 50,
                },
                {
                    url: '',
                    width: 142,
                    height: 142,
                    y: 656,
                    x: 390,
                    borderRadius: 140,
                },
            ],
        },
        titleList: [
            [
                '我是',
                'create_name',
                '，4.23世界读书日，我把《',
                'resource_name',
                '》读给你听',
            ],
            ['4.23世界读书日，读书赢好礼，一起来读书吧！'],
            ['读书就像旅行，4.23世界读书日，让我用声音，带你探索世界'],
            ['朗朗书声如春风，4.23世界读书日，让我读给你听！'],
            ['读书让我快乐，喜阅生活从今天开始，我是朗读者，读给你听'],
            ['不负好春光，读书正当时！4.23世界读书日，一起读书赢好礼！'],
        ],
    },
    // 公开赛海报
    {
        posterConfig: {
            pixelRatio: 3,
            width: 571,
            height: 956,
            debug: false,
            texts: [
                {
                    x: 49,
                    y: 544,
                    text: '',
                    fontSize: 30,
                    color: '#333',
                    opacity: 1,
                    marginRight: 10,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1210,
                    textOverflow: 'ellipsis',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'http://aitiaozhan.oss-cn-beijing.aliyuncs.com/school-events-mobile/openGame-poster.png',
                    width: 571,
                    height: 956,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 457,
                    height: 259,
                    y: 242,
                    x: 50,
                },
                {
                    url: '',
                    width: 161,
                    height: 161,
                    y: 693,
                    x: 198,
                },
            ],
        },
        titleList: [
            [
                '我的作品《',
                'resource_name',
                '》，【我正在参加爱挑战网络预选赛】,快来给我点赞吧！',
            ],
        ],
    },
    {
        posterConfig: {
            width: 570,
            height: 820,
            debug: false,
            texts: [
                {
                    x: 60,
                    y: 583,
                    text: '',
                    fontSize: 28,
                    color: '#DB4E0E',
                    opacity: 1,
                    marginRight: 10,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1210,
                    textOverflow: 'ellipsis',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/h5/wuyi-poster.png',
                    width: 570,
                    height: 820,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 469,
                    height: 315,
                    y: 233,
                    x: 50,
                },
                {
                    url: '',
                    width: 142,
                    height: 142,
                    y: 645,
                    x: 400,
                    borderRadius: 140,
                },
            ],
        },
        titleList: [
            ['了解劳动乐趣，感受父母辛劳，一起来欣赏下我的劳作成果吧！'],
            ['我是劳动小能手，传承勤劳好家风，大家一起动起来！'],
            ['争当劳动之星，就差你的赞了，快来！'],
        ],
    },
    {
        posterConfig: {
            width: 600,
            height: 775,
            debug: false,
            texts: [
                {
                    x: 89,
                    y: 552,
                    text: '',
                    fontSize: 28,
                    color: '#fff',
                    opacity: 1,
                    marginRight: 10,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1100,
                    textOverflow: 'ellipsis',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/h5/liuyi-poster2.png',
                    width: 600,
                    height: 775,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 455,
                    height: 257,
                    y: 262,
                    x: 63,
                    borderRadius: 20,
                },
                {
                    url: '',
                    width: 90,
                    height: 90,
                    y: 624,
                    x: 422,
                    borderRadius: 80,
                },
            ],
        },
        titleList: [
            ['七彩童年， 快乐成长秀风采！快来围观我的作品'],
            ['快乐六一！我是才艺小达人，等你来打call~'],
            ['欢乐儿童节，精彩才艺SHOW出来！来看看吧'],
            ['我正在参加“快乐成长秀风采活动”为我点赞吧！'],
            ['快乐儿童节，我来秀才艺！来点赞吧，就差你啦~'],
        ],
    },
    {
        posterConfig: {
            width: 570,
            height: 820,
            debug: false,
            texts: [
                {
                    x: 50,
                    y: 600,
                    text: '',
                    fontSize: 28,
                    color: '#FF574A',
                    opacity: 1,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 600,
                    textOverflow: 'ellipsis',
                    textAlign: 'left',
                    baseLine: 'middle',
                },
                {
                    x: 190,
                    y: 516,
                    text: '',
                    textAlign: 'center',
                    fontSize: 32,
                    color: '#fff',
                    opacity: 1,
                    lineNum: 1,
                    lineHeight: 174,
                    textOverflow: 'ellipsis',
                    width: 680,
                    zIndex: 100,
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/h5/qiyi-poster.png',
                    width: 570,
                    height: 820,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 470,
                    height: 316,
                    y: 254,
                    x: 48,
                    borderRadius: 20,
                },
                {
                    url: '',
                    width: 110,
                    height: 110,
                    y: 684,
                    x: 434,
                    borderRadius: 100,
                    color: '9882ff',
                },
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/h5/qiyi-bar-poster.png',
                    width: 362,
                    height: 74,
                    y: 484,
                    x: 5,
                },
            ],
        },
        titleList: [
            ['“爱挑战”代言人，舍我其谁！快为我点赞吧！'],
            ['“爱挑战”代言人，非我莫属，快为我点赞吧！'],
        ],
    },
    // 11是直播，没有作品详情
    {},
    {
        posterConfig: {
            width: 570,
            height: 820,
            debug: false,
            texts: [
                {
                    x: 50,
                    y: 600,
                    text: '',
                    fontSize: 28,
                    color: '#FF574A',
                    opacity: 1,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 600,
                    textOverflow: 'ellipsis',
                    textAlign: 'left',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/h5/clocked_poster.png',
                    width: 570,
                    height: 820,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 470,
                    height: 316,
                    y: 254,
                    x: 48,
                    borderRadius: 20,
                    color: 'FFA69F',
                },
                {
                    url: '',
                    width: 110,
                    height: 110,
                    y: 684,
                    x: 434,
                    borderRadius: 100,
                },
            ],
        },
        titleList: [
            ['我在参加爱挑战暑期打卡活动，就差你的赞啦！'],
            ['我这么努力打卡进步，你就给个赞鼓励下嘛！'],
            ['我又发布新作品啦，快来看！'],
        ],
    },
    {
        posterConfig: {
            width: 570,
            height: 820,
            debug: false,
            texts: [
                {
                    x: 60,
                    y: 583,
                    text: '',
                    fontSize: 28,
                    color: '#DB4E0E',
                    opacity: 1,
                    marginRight: 10,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1210,
                    textOverflow: 'ellipsis',
                    baseLine: 'middle',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/h5/wuyi-poster.png',
                    width: 570,
                    height: 820,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 469,
                    height: 315,
                    y: 233,
                    x: 50,
                },
                {
                    url: '',
                    width: 142,
                    height: 142,
                    y: 645,
                    x: 400,
                    borderRadius: 140,
                },
            ],
        },
        titleList: [
            ['体验劳动乐趣，感受父母辛劳！来看看我的劳动成果'],
            ['我是劳动小能手，传承勤劳好家风，一起动起来！'],
            ['争当劳动之星，就差你的赞了，快来支持我！'],
            ['幸福的生活哪里来，要靠劳动来创造~来为我点赞吧'],
        ],
    },
    {
        posterConfig: {
            width: 750,
            height: 1050,
            debug: false,
            texts: [
                {
                    x: 375,
                    y: 656,
                    text: '',
                    fontSize: 32,
                    color: '#004137',
                    opacity: 1,
                    lineHeight: 40,
                    lineNum: 1,
                    width: 1210,
                    textOverflow: 'ellipsis',
                    textAlign: 'center',
                },
            ],
            images: [
                {
                    url:
                        'https://aitiaozhan.oss-cn-beijing.aliyuncs.com/h5/shiyi-poster.png',
                    width: 750,
                    height: 1050,
                    y: 0,
                    x: 0,
                },
                {
                    url: '',
                    width: 532,
                    height: 364,
                    y: 236,
                    x: 108,
                },
                {
                    url: '',
                    width: 160,
                    height: 160,
                    y: 672,
                    x: 484,
                    borderRadius: 160,
                },
            ],
        },
        titleList: [
            ['我正在参加趣味诗词大闯关，跟我一起来！'],
            ['诵读诗词，传承经典'],
        ],
    },
];

export default detailConf;
